
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttznuwxafuodsmmqhfda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0em51d3hhZnVvZHNtbXFoZmRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MTg4NzUsImV4cCI6MjA2MjE5NDg3NX0.lYXB146QHEQ4tN05kYk4JSUIVObC9qos0scrdraijeM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
